services:
  postgres:
    image: postgres:15
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  migrate:
    image: golang:1.24
    working_dir: /app
    volumes:
      - ./seg_service:/app
    depends_on:
      - postgres
    env_file:
      - .env
    entrypoint: ["go", "run", "github.com/pressly/goose/v3/cmd/goose@latest", "-dir", "migrations", "postgres", "${POSTGRES_DSN}", "up"]

  seg_service:
    build:
      context: .
      dockerfile: seg_service/Dockerfile
    depends_on:
      - postgres
      - redis
      - migrate
    env_file:
      - .env
    environment:
      POSTGRES_DSN: ${POSTGRES_DSN}
      REDIS_ADDR: ${REDIS_ADDR}
      REDIS_PASS: ${REDIS_PASS}
      HTTP_PORT: ${HTTP_PORT}
    ports:
      - "8080:8080"

volumes:
  pgdata: 